### ISSUE TITLE
License

### ISSUE THREAD

**Issue by buchanae** [ga4gh/task-execution-schemas#43]
This repo should include licensing information. Is the MIT license acceptable?

**Comment by geoffjentry** [comment]
Good point!

Other than I tend to have a preference towards licenses on the BSD side of the license family tree (which I consider MIT to be) instead of the GPL side I don't have much opinion. I'd be :+1: to MIT.

FWIW our lawyers requested that we use the BSD 3-clause for things. I don't pretend to know the reasons why but now I tend to use that as a mental starting point since a) I'm biased towards BSD and b) some group of lawyers seemed to think it was a good idea. 

Also because I'm always curious why people choose the licenses they do I'm curious why you wound up on MIT. I find it usually winds up somewhere between a ¯\_(ツ)_/¯ and "because that's just what someone told me to do" but it's still always worth asking :)

**Comment by adamstruck** [comment]
I don't have a strong opinion either way, but I did notice that of the GA4GH repos that have a license, it is the Apache 2.0 license.

**Comment by geoffjentry** [comment]
Oh good point @adamstruck - now that you mention it I think that's intentional.

**Comment by buchanae** [comment]
@geoffjentry 

> Also because I'm always curious why people choose the licenses they do I'm curious why you wound up on MIT. I find it usually winds up somewhere between a ¯_(ツ)_/¯ and "because that's just what someone told me to do" but it's still always worth asking :)

My research (years ago) on the topic led me to MIT because it's the simplest and least restrictive, and also widely accepted and understood. I shy away from GPL because it requires derivative works to be similarly licensed, and I've seen that trip up projects a few times in the past. Apache 2.0 has content regarding patents, which I don't know enough about to care, so I end up not using it.

All that said, sounds like Apache 2.0 is the way to go here.

**Comment by buchanae** [comment]
Who is the copyright owner? "GA4GH"? I looked at a few other ga4gh repos, but they all forgot to update the copyright year/owner line.

**Comment by buchanae** [comment]
@briandoconnor Any guidance here?
